### ISSUE TITLE
`@stream` example not working yet

### ISSUE THREAD

**Issue by saihaj** [saihaj/graphql-ts-node-advanced-tutorial#1]
So links is a list of Links  I don’t understand this error. 
![image](https://user-images.githubusercontent.com/44710980/141662196-dc2bc885-905b-446b-a82c-c92e46c3271f.png)

**Comment by n1ru4l** [comment]
Have you tried a nullable list?

**Comment by saihaj** [comment]
I tried a simple `[String]` list but I will try out a `ObjectType`

**Comment by n1ru4l** [comment]
SO I double verified. Once `Feed.links` returns `[Link!]` instead of `[Link!]!`, it works. It might be that graphql-js implementation does not unwrap NonNullable types?

**Comment by saihaj** [comment]
>  It might be that graphql-js implementation does not unwrap NonNullable types?

Yeah looks like it can't unwrap non-nullable items. I made a reproduction and posted in https://github.com/robrichard/defer-stream-wg/discussions/25
