### ISSUE TITLE
`@skipAuth` not working on nested objects?

### ISSUE THREAD

**Issue by saihaj** [saihaj/graphql-ts-node-advanced-tutorial#3]
```graphql
directive @skipAuth on FIELD_DEFINITION

type Query {
  info: String! @skipAuth
  me: User! @skipAuth
}

type Mutation {
  login(email: String!, password: String!): AuthPayload @skipAuth
}

type AuthPayload {
  token: String
  user: User
}

type User {
  id: ID!
  name: String!
  email: String!
  links: [Link!]!
}
```

So if I try to get info or me everything is working as i expect. But when I run login mutation to get token I get unauthenticated error on
```json
"path": [
  "login",
  "token"
]
```

**Comment by n1ru4l** [comment]
![image](https://user-images.githubusercontent.com/14338007/142413355-ae652145-0746-4b6d-be3f-36048c571049.png)

Makes sense, because the `@skipAuth` is not applied on the fields that are selected by the operation?

**Comment by saihaj** [comment]
If I add to `type` shouldn't that apply to all the types?

**Comment by saihaj** [comment]
wait nvm `FIELD_DEFINITION`
